version: "3.3"

services:
  node:
    container_name: telegram_web_bot
    restart: always
    image: node:20.14.0
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - web_bot

    command: bash -c "npm install && npm run start:prod"

networks:
  web_bot:
    driver: bridge
